### PR TITLE
Add support for `np.clip` and `ndarray.clip`.

### LINKED ISSUE #3465: Add support for np.clip
## Feature request

Currently `np.clip(a, a_min, a_max, out=None)` and `a.clip(a_min=None, a_max=None, out=None)` are not supported by `@njit`.

I tried to implement this myself, but am having trouble installing `llvm-6.0` in order to test my development branch locally. So, without knowing what I'm doing (first time looking at `numba` source code), this was my blind attempt implementing `np.clip(...)`:

```python
# File: numba/targets/arrayobj.py

@lower_builtin(np.clip, types.Array)
def array_clip(context, builder, sig, args):
    def np_clip_impl(a, a_min, a_max, out=None):
        if out is None:
            out = np.empty_like(a)
        for i in range(len(a)):
            if a[i] < a_min:
                out[i] = a_min
            elif a[i] > a_max:
                out[i] = a_max
            else:
                out[i] = a[i]
        return out

    return context.compile_internal(builder, np_clip_impl, sig, args)
```

Following the pattern in #3462, I'm guessing that something like this is also needed (for `a.clip(...)`):

```python
# File: numba/targets/arrayobj.py

@overload_method(types.Array, 'clip')
def array_clip(a, a_min, a_max, out=None):
    def impl(a, a_min, a_max, out=None):
        return np.clip(a, a_min, a_max, out)
    return impl
```

**Edit**: The above implementation is incomplete since the signature for `a.clip` is:
```
    a.clip(min=None, max=None, out=None)
```
Note the default values, which are not present for `np.clip`.

Furthermore, `None` can be passed to `np.clip` for `a_min` or `a_max`, in which case the lower or upper bounds are ignored, respectively.

### PR DESCRIPTION
**Pull request by arvoelke**
As title.

Fixes #3465

### CODE REVIEW

**Comment by arvoelke** [comment]
Note that I had to comment out a couple tests because they are currently broken! Something to do with `None` types. Help / pointers would be appreciated. Here is a snippet of the error from uncommenting the `cfunc(a, None, None)` test:

```
py.test numba/tests/test_array_methods.py::TestArrayMethods::test_clip
```

```
           numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
E           Invalid use of Function(<function clip at 0x7f5ab69b6158>) with argument(s) of type(s): (array(float64, 1d, C), none, none, none)
E            * parameterized
E           In definition 0:
E               TypingError: Failed in nopython mode pipeline (step: nopython frontend)
E           Invalid use of Function(<built-in function lt>) with argument(s) of type(s): (float64, none)
E           Known signatures:
E            * (bool, bool) -> bool
E            * (int8, int8) -> bool
E            * (int16, int16) -> bool
E            * (int32, int32) -> bool
E            * (int64, int64) -> bool
E            * (uint8, uint8) -> bool
E            * (uint16, uint16) -> bool
E            * (uint32, uint32) -> bool
E            * (uint64, uint64) -> bool
E            * (float32, float32) -> bool
E            * (float64, float64) -> bool
E            * parameterized
E           In definition 0:
E               All templates rejected
E           In definition 1:
E               All templates rejected
E           In definition 2:
E               All templates rejected
E           In definition 3:
E               All templates rejected
E           In definition 4:
E               All templates rejected
E           In definition 5:
E               All templates rejected
E           In definition 6:
E               All templates rejected
E           This error is usually caused by passing an argument of a type that is unsupported by the named function.
E           [1] During: typing of intrinsic-call at /home/arvoelke/CTN/arvoelke-numba/numba/targets/arrayobj.py (1713)
E           
E           File "numba/targets/arrayobj.py", line 1713:
E               def np_clip_impl(a, a_min, a_max, out=None):
E                   <source elided>
E                   for i in range(len(a)):
E                       if a_min is not None and a[i] < a_min:
E                       ^
E           
E               raised from /home/arvoelke/CTN/arvoelke-numba/numba/typeinfer.py:864
```

File: numba/tests/test_array_methods.py [hunk 1]
```diff
@@ -894,6 +900,27 @@ def test_imag(self):
         z = x + 1j*y
         np.testing.assert_equal(pyfunc(z), cfunc(z))
 
+    def test_clip(self):
+        a = np.linspace(-10, 10, 101)
+        pyout = np.empty_like(a)
+        cout = np.empty_like(a)
```
Comment (arvoelke) [inline numba/tests/test_array_methods.py]: Note to self: these should be moved inside of the for loop, to prevent cross-contamination from the last test (`np.testing.assert_equal(pyout, cout)`).

**Comment by arvoelke** [comment]
I'm also encountering some strange behaviour on this branch when it comes to using this overloaded `np.clip` within larger programs. For example, when adding this line to my test function:

```
jit(nopython=True)(lambda a: np.expm1(np.clip(a, -5, 5)))(a)
```

This raises the error:
```
...
E           Invalid use of Function(<ufunc 'expm1'>) with argument(s) of type(s): (?array(float64, 1d, C))
E            * parameterized
E           In definition 0:
E               TypingError: can't resolve ufunc expm1 for types (?array(float64, 1d, C),)
E               raised from /home/arvoelke/CTN/arvoelke-numba/numba/typing/npydecl.py:105
E           This error is usually caused by passing an argument of a type that is unsupported by the named function.
E           [1] During: resolving callee type: Function(<ufunc 'expm1'>)
...
```

The strange thing is I can get this to work if I replace the `np.clip` with a call to `np_clip_impl` decorated with `@njit`. And furthermore this inner-decorator turns out to be necessary. So there seems to be some difference in the type-inference between my `@overload`ed implementation and my `@njit`ed implementation.

File: numba/targets/arrayobj.py [hunk 2]
```diff
@@ -1702,6 +1702,31 @@ def imp(ary):
...
 
 
+@overload(np.clip)
+def np_clip(a, a_min, a_max, out=None):
+    def np_clip_impl(a, a_min, a_max, out=None):
+        if a_min is None and a_max is None:
+            raise ValueError("array_clip: must set either max or min")
+        if out is None:
+            out = np.empty_like(a)
+        for i in range(len(a)):
```
Comment (arvoelke) [inline numba/targets/arrayobj.py]: Note to self: use `for index, val in np.ndenumerate(a):` and add multi-dimensional tests.

**Comment by arvoelke** [comment]
Could someone please provide me with a lead on why `jit(nopython=True)(lambda a: np.expm1(np.clip(a, -5, 5)))(a)` throws the above error on this branch? Related PRs / issues / code / docs would be appreciated.

**Comment by seibert** [comment]
Speculating here, I think it is related to how Numba handles "optional" types, which are types where the value is either of a specific type (like `float64`) or `None`.  It is possible that type inference is behaving oddly for some reason.

@sklam: Can you offer some advice here?

**Comment by stuartarchibald** [comment]
I think the "optional" return type is because type inference has to accommodate `out` being `None` or some known type, the returned type is effectively `array or None`.

The issue present arises because `ufuncs` have no handling for optional types, as an example:

```python
from numba import njit
import numpy as np

def foo(A):
    return np.cos(A)

njit("(float64[:],)")(foo)(np.arange(10.)) # fine
njit("(optional(float64[:]),)")(foo)(np.arange(10.)) # broken
```

To force type inference to determine the type, specialisation is needed:

```python
def _alloc_out(a, X): # dummy function that takes the arg we need to resolved and information to do so
    pass

@overload(_alloc_out)
def _alloc_out_impl(a, X): # overload the dummy function returning an implementation determined by whether `X` is a None-like type.
    if X is None or isinstance(X, types.NoneType):
        def impl(a, X):
            return np.empty_like(a)
    else:
        def impl(a, X):
            return X
    return impl

@overload(np.clip)
def np_clip(a, a_min, a_max, out=None):
    def np_clip_impl(a, a_min, a_max, out=None):
        if a_min is None and a_max is None:
            raise ValueError("array_clip: must set either max or min")
        ret = _alloc_out(a, out) # Force typing to explicitly resolve the type of `ret`, the function call will be inlined
        for i in range(len(a)):
            if a_min is not None and a[i] < a_min:
                ret[i] = a_min
            elif a_max is not None and a[i] > a_max:
                ret[i] = a_max
            else:
                ret[i] = a[i]
        return ret
    return np_clip_impl
```
by delegating the compilation of `out` through a function that explicitly handles the `None` vs. known array (i.e. resolves the `optional`), the type can be fully determined.

File: numba/targets/arrayobj.py (hunk 2 above)
Comment (stuartarchibald) [reply numba/targets/arrayobj.py]: Assuming that fixing `np.ndenumerate(scalar)` may well be complicated, could the implementation just branch to an function that specifically deals with scalars as a workaround? e.g.

```python
@overload(np.clip)
def np_clip(a, a_min, a_max, out=None):
    if isinstance(a, types.Number):
       def np_clip_impl(a, a_min, a_max, out=None):
            # scalar impl
    elif isinstance(a, types.Array):
        def np_clip_impl(a, a_min, a_max, out=None):
            # array impl
    return np_clip_impl
```

**Comment by arvoelke** [comment]
Thanks @stuartarchibald. I pushed a commit with your change. That did the trick in getting `jit(nopython=True)(lambda a: np.expm1(np.clip(a, -5, 5)))(a)` to work! Your explanation also makes sense. I didn't add this explicitly as a test case though since it seems out of place? I just tested it manually offline.

I also had to do something similar to handle the possibilities of `a_min` and/or `a_max` being `None`. Otherwise my tests didn't pass. Are there ways to simplify my code while still passing all the tests?

It also supports multi-dimensional arrays now. The scalar case is broken (as in #3469), which I could fix with more type-specific implementations, but this would double the amount of code to handle all the possibilities again -- unless I'm missing a cleaner way of doing this.

**Comment by arvoelke** [comment]
> That did the trick in getting `jit(nopython=True)(lambda a: np.expm1(np.clip(a, -5, 5)))(a)` to work!

After some more follow-up, it appears that:
```python
jit(nopython=True)(lambda a: np.expm1(a.clip(-5, 5)))(a)
```
is still broken for the same reason (difference is between `np.clip` and `a.clip`). Do I need to copy-paste this approach to get a type-specific implementation for the `@overload_method(types.Array, 'clip')` as well?

**Comment by stuartarchibald** [comment]
@arvoelke RE https://github.com/numba/numba/pull/3468#issuecomment-438046427 I took a look at this and was a bit puzzled, so dug around a bit and think it's a bug, reported it here https://github.com/numba/numba/issues/3489.

For now, please could you try just dropping the `out` kwarg in the array method implementation and if that works it can be documented as such. That gets the functionality at least mostly working whilst #3489 is fixed. How does that sound?

Also, as it stands right now, the cut-off for the 0.41.0 Release Candidate is Monday 18th Nov if you were hoping for it to be in the next release? (we'll endeavour to get review turned around in time!)

Thanks.

**Comment by arvoelke** [comment]
> For now, please could you try just dropping the `out` kwarg in the array method implementation and if that works it can be documented as such. That gets the functionality at least mostly working whilst #3489 is fixed. How does that sound?

I gave this a shot, but it appears as though the above snippet still fails when `a_min` or `a_max` are left out, i.e., `jit(nopython=True)(lambda a: np.expm1(a.clip(-5)))(a)` still fails. This is with the code changed to:

```python
@overload_method(types.Array, 'clip')
def array_clip(a, a_min=None, a_max=None):
    # TODO: out argument not supported (see issue #3489)
    def impl(a, a_min=None, a_max=None):
        return np.clip(a, a_min, a_max)
    return impl
```

Reminder that these optional arguments have defaults for `ndarray.clip` but not for `np.clip`.

If on the other hand I remove the defaults, as in:

```python
@overload_method(types.Array, 'clip')
def array_clip(a, a_min, a_max):
    # TODO: out argument not supported (see issue #3489)
    def impl(a, a_min, a_max):
        return np.clip(a, a_min, a_max)
    return impl
```

then `jit(nopython=True)(lambda a: np.expm1(a.clip(-5, None)))(a)` works just fine.

So I assume this is connected to #3489 in the same manner.

Since these defaults are a pretty significant feature of `ndarray.clip`, should we perhaps omit this implementation for now, and document only `np.clip` support under the list of [other functions](https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#other-functions)? Or is it better to have a mostly-working implementation associated with a known bug?

**Comment by arvoelke** [comment]
In the interest of streamlining our conversation and the review process, I've pushed a commit that removes `ndarray.clip` support, documents `np.clip` support instead, adds a couple more test cases, and documents the two outstanding bugs in the code. We can always unroll this commit if that's no good.

**Comment by arvoelke** [comment]
`azure` produced 3 build failures, all in the same way for one of the new tests I added:

```
2018-11-15T21:08:03.6820924Z ======================================================================
2018-11-15T21:08:03.6820999Z FAIL: test_clip (numba.tests.test_array_methods.TestArrayMethods)
2018-11-15T21:08:03.6821062Z ----------------------------------------------------------------------
2018-11-15T21:08:03.6821165Z Traceback (most recent call last):
2018-11-15T21:08:03.6821219Z   File "D:\a\1\s\numba\tests\test_array_methods.py", line 934, in test_clip
2018-11-15T21:08:03.6821274Z     jit(nopython=True)(lower_clip_result)(a))
2018-11-15T21:08:03.6821383Z   File "C:\Miniconda\envs\testenv\lib\site-packages\numpy\testing\_private\utils.py", line 347, in assert_equal
2018-11-15T21:08:03.6821448Z     return assert_array_equal(actual, desired, err_msg, verbose)
2018-11-15T21:08:03.6821555Z   File "C:\Miniconda\envs\testenv\lib\site-packages\numpy\testing\_private\utils.py", line 865, in assert_array_equal
2018-11-15T21:08:03.6821615Z     verbose=verbose, header='Arrays are not equal')
2018-11-15T21:08:03.6821675Z   File "C:\Miniconda\envs\testenv\lib\site-packages\numpy\testing\_private\utils.py", line 789, in assert_array_compare
2018-11-15T21:08:03.6821773Z     raise AssertionError(msg)
2018-11-15T21:08:03.6821819Z AssertionError: 
2018-11-15T21:08:03.6821872Z Arrays are not equal
2018-11-15T21:08:03.6821961Z skipped CUDA tests
2018-11-15T21:08:03.6822006Z skipped CUDA tests
2018-11-15T21:08:03.6822050Z skipped HSA tests
2018-11-15T21:08:03.6822093Z skipped HSA tests
2018-11-15T21:08:03.6822988Z 
2018-11-15T21:08:03.6823066Z (mismatch 4.950495049504951%)
2018-11-15T21:08:03.6823127Z  x: array([ -0.993262,  -0.993262,  -0.993262,  -0.993262,  -0.993262,
2018-11-15T21:08:03.6823228Z         -0.993262,  -0.993262,  -0.993262,  -0.993262,  -0.993262,
2018-11-15T21:08:03.6823284Z         -0.993262,  -0.993262,  -0.993262,  -0.993262,  -0.993262,...
2018-11-15T21:08:03.6823338Z  y: array([ -0.993262,  -0.993262,  -0.993262,  -0.993262,  -0.993262,
2018-11-15T21:08:03.6823434Z         -0.993262,  -0.993262,  -0.993262,  -0.993262,  -0.993262,
2018-11-15T21:08:03.6823489Z         -0.993262,  -0.993262,  -0.993262,  -0.993262,  -0.993262,...
2018-11-15T21:08:03.6823520Z 
2018-11-15T21:08:03.6824181Z ======================================================================
```

This test calls the function:
```python
def lower_clip_result(a):
    return np.expm1(np.clip(a, -5, 5))
```

Maybe I should use a function other than `expm1`? Seems like something to do with numerical precision on the `np15` builds.

**Comment by seibert** [comment]
you can use `assert_array_almost_equal` for the test

**Comment by arvoelke** [comment]
> you can use `np.testing.assert_array_almost_equal` for the test

Thanks. Passed locally and pushed. Surprised that even passed before!

**Comment by arvoelke** [comment]
> Also, as it stands right now, the cut-off for the 0.41.0 Release Candidate is Monday 18th Nov if you were hoping for it to be in the next release? (we'll endeavour to get review turned around in time!)

All of the builds passed this time. Is this ready for review, or should we hold off to fix the `ndarray.clip` issue?

**Comment by seibert** [comment]
I think we need to implement both to avoid confusion for users.  We are planning for 0.42 to be a short dev cycle, with a release in the 3rd week of December, so if we miss 0.41, it will make it there.

**Comment by stuartarchibald** [comment]
Since https://github.com/numba/numba/pull/3704 was merged it should be possible to now implement the part of this feature that was blocked. @arvoelke would you be interested in having another go (after merging master into this branch) and letting us know how you get on?

**Comment by arvoelke** [comment]
After rebasing this onto upstream/master, I now get the following error when running any unit test locally:
```
../../anaconda3/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
numba/__init__.py:25: in <module>
    from .decorators import autojit, cfunc, generated_jit, jit, njit, stencil
numba/decorators.py:12: in <module>
    from .targets import registry
numba/targets/registry.py:5: in <module>
    from . import cpu
numba/targets/cpu.py:11: in <module>
    from .base import BaseContext, PYOBJECT
numba/targets/base.py:20: in <module>
    from numba.pythonapi import PythonAPI
numba/pythonapi.py:18: in <module>
    PY_UNICODE_1BYTE_KIND = _helperlib.py_unicode_1byte_kind
E   AttributeError: module 'numba._helperlib' has no attribute 'py_unicode_1byte_kind'
```

I tried `conda upgrade -c numba llvmlite` but got no changes. Is there something else I need to do to bring things up to sync?

**Comment by arvoelke** [comment]
I'm still having issues in the context of #3489 regarding the above discussion / example. Although you can see the exact code+error currently in Travis CI, I thought it would be more productive to come up with a minimal example that reproduces the kind of problems I'm seeing (note it's not the exact same error, but I believe it's tapping into the same issue).

```python
import numpy as np
from numba import njit, types
from numba.extending import overload_method, overload

def foo(arr, a=None):
    return arr

def foo_impl(arr, a=None):
    if a is None or isinstance(a, types.NoneType):
        def impl(arr, a=None):
            return arr
    else:
        def impl(arr, a=None):
            return arr + a
    return impl

overload(foo)(foo_impl)
overload_method(types.Array, 'foo')(foo_impl)

@njit
def bar1(A):
    return foo(A)

@njit
def bar2(A):
    return A.foo()

Z = np.arange(2)

print(bar1(Z))
print(bar2(Z))
```



```
[0 1]
Traceback (most recent call last):
  File "minimal-reproducer.py", line 31, in <module>
    print(bar2(Z))
  File "/home/arvoelke/CTN/arvoelke-numba/numba/dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/arvoelke/CTN/arvoelke-numba/numba/dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "/home/arvoelke/CTN/arvoelke-numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function add>) with argument(s) of type(s): (array(int64, 1d, C), none)
Known signatures:
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
 * (float32, float32) -> float32
 * (float64, float64) -> float64
 * (complex64, complex64) -> complex64
 * (complex128, complex128) -> complex128
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
In definition 12:
    All templates rejected with literals.
In definition 13:
    All templates rejected without literals.
In definition 14:
    All templates rejected with literals.
In definition 15:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at minimal-reproducer.py (14)

File "minimal-reproducer.py", line 14:
        def impl(arr, a=None):
            return arr + a
            ^

[1] During: lowering "$0.5 = call $0.4(func=$0.4, args=[], kws=(), vararg=None)" at minimal-reproducer.py (26)
```

The weird thing is it works for `@overload` (bar1) but not for `@overload_method` (bar2). The crux of the issue seems to have something to do with type-inference on `arr + a`. 

In the context of this PR, this snippet corresponds to `arr.clip(a_min, a_max)` in that `a_min` (which can be `None`) plays a role in the return value (when it is not `None`). 

Somewhat relatedly... it just occurred to me that I'm failing to support and test an obscure use-case of `np.clip`, in which `a_min` and/or `a_max` can be `array_like`. According to the [np.clip documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html):

> If a_min or a_max are array_like, then the three arrays will be broadcasted to match their shapes.

```
>>> a = np.arange(10)
>>> a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> np.clip(a, [3, 4, 1, 1, 1, 4, 4, 4, 4, 4], 8)
array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8])
```

Things undoubtedly become more complicated when `a` is also multi-dimensional.

I don't know how I missed this until now... and I apologize that I don't really have the bandwidth right now to figure out how to support that properly in addition to the above issue. I should either hand this off or postpone it until I have some time (probably March).

**Comment by stuartarchibald** [comment]
@arvoelke thanks for looking at this again. The issue presented is due to the variable `a` being of type `omitted(default=None)` which isn't picked up in the `if` condition to branch to the implementation that doesn't contain `arr + a`. This sort of thing should work fine:
```python
import numpy as np
from numba import njit, types
from numba.extending import overload_method, overload

def foo_impl(arr, a=None):
    if a is None or isinstance(a, types.NoneType) or getattr(a, 'value', False) is None:
        def impl(arr, a=None):                    # ^^^^^^ new condition for `omitted(default=None)` handling
            return arr
    else:
        def impl(arr, a=None):
            return arr + a
    return impl

overload_method(types.Array, 'foo')(foo_impl)

@njit
def bar2(A):
    print(A.foo())
    print(A.foo(7))

Z = np.arange(2)

print(bar2(Z))
```
This WIP branch: https://github.com/numba/numba/pull/3592 has a feature which propagates constant `None` arguments through the code ahead of type inference and prunes branches that can be statically determined as dead. With that patchset applied to Numba master, this works:
```python
import numpy as np
from numba import njit, types
from numba.extending import overload_method, overload

def foo_impl(arr, a=None):
    def impl(arr, a=None):
        if a is None:
            return arr
        else:
            return arr + a
    return impl

overload_method(types.Array, 'foo')(foo_impl)

@njit
def bar2(A):
    print(A.foo())
    print(A.foo(7))

Z = np.arange(2)

print(bar2(Z))
```
as the `a = omitted(default=None)` gets propagated through and then `arr + a` branch gets pruned, then type inference runs and has no problem. I really need to finish working on it!

If you'd like to complete this feature, then there's no pressure time wise, it can be picked up again in March. Equally if you'd rather one of the core developers continues with it that's fine too. Entirely up to you :)

**Comment by arvoelke** [comment]
> If you'd like to complete this feature, then there's no pressure time wise, it can be picked up again in March. Equally if you'd rather one of the core developers continues with it that's fine too. Entirely up to you :)

Thanks again for describing the fix+details, and that PR looks very useful. I'd like to continue working on this, as I think this is a very valuable exercise and I'd like to eventually gain some understanding of the internals of Numba. I will pick this up again in March when I have some spare cycles for dev work!

**Comment by stuartarchibald** [comment]
> I will pick this up again in March when I have some spare cycles for dev work!

Great, thanks, looking forward to hearing from you then.

**Comment by stuartarchibald** [comment]
Just checking in on the state of this PR. @arvoelke was wondering if you have time to address the above, if not, don't worry, one of the core developers can take over to do the fixes. Thanks.

**Comment by arvoelke** [comment]
My bad for letting this slip. It would be good if someone else could take over. A big thing that was slowing me down here was the use-case "in which a_min and/or a_max can be array_like." See above for documentation / etc. If the concern here isn't about matching the entire spec for `np.clip` then the main thing remaining is applying the idea from https://github.com/numba/numba/pull/3468#issuecomment-461050278. If there are questions while wrapping this up about the history of attempts in this PR just let me know. Still very interested in following this along. Thanks!

**Comment by stuartarchibald** [comment]
@arvoelke thanks for letting us know and your work on this so far. One of the core devs will pick it up.

**Comment by makslevental** [comment]
any chance this will ever get merged?

**Comment by esc** [comment]
> any chance this will ever get merged?

Thanks for asking about this! Yes, there is definitely a chance that it will become merged. As soon as it becomes a priority of one of the core devs or when someone from the community picks it up and drives it to completion.

**Comment by arvoelke** [comment]
> any chance this will ever get merged?

If this is something you need immediately (i.e., before merging), you're okay with calling `np.clip` as opposed to using the method `a.clip`, you don't need the `out` argument, and specify both `a_min` and `a_max` as scalars (as opposed to being optional, or arrays)... then you could use the snippet in this comment here: https://github.com/numba/numba/issues/3465#issuecomment-435355209. Copied below for clarity:

```python
@extending.overload(np.clip)
def np_clip(a, a_min, a_max, out=None):
    def np_clip_impl(a, a_min, a_max, out=None):
        if out is None:
            out = np.empty_like(a)
        for i in range(len(a)):
            if a[i] < a_min:
                out[i] = a_min
            elif a[i] > a_max:
                out[i] = a_max
            else:
                out[i] = a[i]
        return out
    return np_clip_impl
```

Extending this to handle all of the different ways in which `np.clip` and `a.clip` can be called has been the crux of this PR. :)

**Comment by kernc** [comment]
Since those two are already implemented, how about implementing `np.clip` in terms of `np.maximum` and `np.minimum`?
```py
def np_clip(a, a_min, a_max, out=None):
    if out is None:
        out = np.empty_like(a)
    out[:] = np_minimum(np_maximum(a, a_min), a_max)
    return out
```
This seems to cover various input cases ...

**Comment by gmarkall** [comment]
PR #6808 started to continue this work.

**Comment by stuartarchibald** [comment]
Closing this as https://github.com/numba/numba/pull/6808 continues. Thanks for your work on the initial implementation @arvoelke .
