### ISSUE TITLE
cannot import name 'cffi_support' from 'numba' 

### ISSUE THREAD

**Issue by scarlehoff** [numba/numba#5583]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

### Bug

I'm installing numba directly with pip, then finding out the `cffi_support` module does not exist anymore. Given it is not mentioned in the changelog and that is still in the docs (and used here https://github.com/numba/numba/blob/master/examples/notebooks/Accessing%20C%20Struct%20Data.ipynb) I'm guessing the package that got uploaded to pypi is bugged somehow.

### Steps to reproduce the issue:
Create a fresh virtual environment and install numba:
```
virtualenv test
source test/bin/activate
pip install numba
```

then try to import `cffi_support`

```
>>> from numba import cffi_support
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'cffi_support' from 'numba' (/$HOME/test/test/lib/python3.8/site-packages/numba/__init__.py)
```

Let me know if you need more information or if any of the thing's here are not supported (be it python 3.8 or using `cffi_support`)

Update: see comment below https://github.com/numba/numba/issues/5583#issuecomment-615370963

**Comment by stuartarchibald** [comment]
Thanks for the report. Numba 0.48->0.49 underwent a huge refactoring, two release candidates were posted for users to check their applications against the proposed changes, I guess this notebook got missed.

As part of this refactoring the `cffi_support` module has been removed, as noted in the source for 0.48.0 its presence was for backwards compatibility only and as an alias for `numba.typing.cffi_utils`:
https://github.com/numba/numba/blob/cc7e7c7cfa6389b54d3b5c2c95751c97eb531a96/numba/cffi_support.py#L1-L6

To get you going with that example and Numba 0.49, cell 4 needs:
```from numba.core.typing import cffi_utils as cffi_support```
https://github.com/numba/numba/blame/master/examples/notebooks/Accessing%20C%20Struct%20Data.ipynb#L98

Hope this helps.

**Comment by scarlehoff** [comment]
Aha! Saw that but since `numba.typing.cffi_utils` didn't work either I thought it made sense to open the issue (missed the core). Fixed my code, and now seems to work fine with 0.49, thank you very much! :D

I'd suggest changing the docs https://numba.pydata.org/numba-doc/dev/user/cfunc.html?highlight=cffi_support#with-cffi
I can open a PR for that but wouldn't want to mess them up with inaccurate information! (also, don't know if the change of the docs is already underway, I guess the release of 0.49 was just today)

**Comment by stuartarchibald** [comment]
> Aha! Saw that but since `numba.typing.cffi_utils` didn't work either I thought it made sense to open the issue (missed the core). Fixed my code, and now seems to work fine with 0.49, thank you very much! :D

No problem, and apologies, the changes were huge and required multiple phases, the odd thing unfortunately got missed. A PR with such a change would be welcomed so as to make the master branch self consistent with the examples.

> I'd suggest changing the docs https://numba.pydata.org/numba-doc/dev/user/cfunc.html?highlight=cffi_support#with-cffi
> I can open a PR for that but wouldn't want to mess them up with inaccurate information! (also, don't know if the change of the docs is already underway, I guess the release of 0.49 was just today)

Yes 0.49 shipped yesterday/today. These examples don't make up part of the docs, there's been discussion of just moving them out to somewhere else so they are easier to maintain and test, but that's for another day. Many thanks!
