### ISSUE TITLE
RAPIDS RMM + Numba Integration: `context.deallocations` is `NoneType`

### ISSUE THREAD

**Issue by kkraus14** [numba/numba#4352]
We're getting the following at the exit of a process with Numba 0.45:
```
Traceback (most recent call last):
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/utils.py", line 745, in _exitfunc
    f()
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/utils.py", line 669, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 1037, in core
    dealloc.add_item(module_unload, handle)
AttributeError: 'NoneType' object has no attribute 'add_item'
```

This didn't happen with previous versions of Numba where I'm wondering if something changed which broke the backdoor integration with RMM and Numba.

I apologize I couldn't give a clearer title, so please feel free to change it if appropriate.

**Comment by sklam** [comment]
This is due to CPython's attempt to free cyclic objects by replacing them with `None` in unpredictable manner during interpreter shutdown.  I usually resolve such issues by adding a `if something is not None` for all offending lines reported, or trying to detect if the CPython is shutting down and do things differently.

I can push a patch for you to test.

**Comment by kkraus14** [comment]
@sklam Are you suggesting a patch for Numba or a patch for RMM? Either way I'm more than happy to test.

**Comment by sklam** [comment]
Patch in numba, but it will need testing against RMM.  This sort of error is very random and depends on the order in which modules are imported.

**Comment by sklam** [comment]
@kkraus14, can you check if https://github.com/numba/numba/pull/4354 resolves the error?  I cannot find a reproducer to trigger the error.

**Comment by kkraus14** [comment]
> @kkraus14, can you check if #4354 resolves the error? I cannot find a reproducer to trigger the error.

Will give it a shot and report back, thanks @sklam!

**Comment by kkraus14** [comment]
@sklam FYI: there's a reproducer within the RAPIDS stack here: https://github.com/rapidsai/cudf/issues/2303
```python
import cudf

df1 = cudf.DataFrame({'a':[1,2,3,4,5]})
df2 = cudf.DataFrame({'a':[1,2,5,4,5]})
res = df1.a == df2.a
b = list(res[res == False].index.values)

print(b)
print('+++++++DONE+++++++')
```

**Comment by kkraus14** [comment]
@sklam confirmed that fixed the issues for me in the simple reproducer above. Running more comprehensive cudf unit tests to check as well.

**Comment by sklam** [comment]
Hmmm.. the reproducer is smaller than I thought it would be.

**Comment by kkraus14** [comment]
Confirmed the unit tests aren't showing this anymore either, so this looks to resolve the issue, thanks!

**Comment by sklam** [comment]
Thanks for confirming the fix.

I did more to find the root cause.  Git bisect points to d4b9e44e5737b80baf6a358159fad96930a51ce8 as the first commit the reproducer start failing.  I am now guessing that this issue will only arise if the primary-context is activated outside of numba.  I will see if I can make a reproducer in the numba testsuite to prevent future regression.

**Comment by ezyang** [comment]
We are seeing this too on Windows. https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test2/39856//console

```
15:12:33 Exception ignored in: <finalize object at 0x5dd98e0160; dead>
15:12:33 Traceback (most recent call last):
15:12:33   File "C:\Jenkins\Miniconda3\lib\site-packages\numba\utils.py", line 669, in __call__
15:12:33     return info.func(*info.args, **(info.kwargs or {}))
15:12:33   File "C:\Jenkins\Miniconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1376, in deref
15:12:33     mem.free()
15:12:33   File "C:\Jenkins\Miniconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1262, in free
15:12:33     self._finalizer()
15:12:33   File "C:\Jenkins\Miniconda3\lib\site-packages\numba\utils.py", line 669, in __call__
15:12:33     return info.func(*info.args, **(info.kwargs or {}))
15:12:33   File "C:\Jenkins\Miniconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 958, in core
15:12:33     deallocations.add_item(driver.cuMemFree, handle, size)
15:12:33 AttributeError: 'NoneType' object has no attribute 'add_item'
```

**Comment by sklam** [comment]
@ezyang, thanks for the report.  I'm prioritizing this issue to be included in the planned 0.45.1 bugfix release.

**Comment by sklam** [comment]
I can confirm that this issue will occur when numba uses an externally created CUDA context.  I now have a reproducer that emulate this situation without external code.
