### ISSUE TITLE
NumPy 2.4

### ISSUE THREAD

**Issue by esc** [numba/numba#10263]
This issue tracks Numba support for NumPy 2.4.

**Comment by stuartarchibald** [comment]
For reference, based on previous release cadence, NumPy 2.4 would be expected around the end of Q4 2025, or start of Q1 2026.

**Comment by charavelg** [comment]
When using numba prerelease (0.63.0b1) with [numpy prerelease ](https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/numpy/2.4.0.dev0/numpy-2.4.0.dev0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl) , it seems[ trapz has been removed](https://github.com/numpy/numpy/commit/e4d64414394cbb2ae62e0f61c3230ba88f537090) from numpy (was deprecated since 2.0). Importing numba  arraymath module raises `AttributeError("module 'numpy' has no attribute 'trapz'").`

**Comment by mattharrison** [comment]
Trying to update my "Effective Pandas" book for Pandas 3. The Pandas 3 rc uses 2.4rc for NumPy.

The book has a short section about using Numba that is currently failing because Numba doesn't work on NumPy 2.4. (Commenting here for awareness and to track)

**Comment by jack-mcivor** [comment]
@mattharrison pandas==3.0.0rc0 will work fine with numpy==2.3
* numba==0.63.1 depends on numpy>=1.22,<2.4
* pandas==3.0.0rc0 depends on numpy>=1.26.0

**Comment by iyanmv** [comment]
`numpy.in1d` was also removed in NumPy 2.4.0

**Comment by krkawzq** [comment]
To be honest, the current Numba implementations feel a bit entry-level. I think we should rewrite the underlying kernels in C++ for maximum performance. Check out the krkawzq/PerturbLab repository—they’ve implemented much faster sparse operators entirely in C++, and the performance gains are impressive!

**Comment by RoyiAvital** [comment]
Any ETA on NumPy 2.4 support? Just to have a rough time when to expect it.

**Comment by iyanmv** [comment]
> Any ETA on NumPy 2.4 support? Just to have a rough time when to expect it.

It will be ready when it's ready, as usual. In the meantime, if you urgently need to use Numba with NumPy 2.4, check e.g. [the patch that Arch Linux](https://gitlab.archlinux.org/archlinux/packaging/packages/python-numba/-/blob/d1832fcbd3643e886b648f360da204110fe5ae80/numpy-2.4.patch) is using for creating the package for their repos.

**Comment by esc** [comment]
> > Any ETA on NumPy 2.4 support? Just to have a rough time when to expect it.
> 
> It will be ready when it's ready, as usual. 

I can confirm this. NumPy 2.4 support will become available with the next Numba release, in all liklihood sometime in Q1 of 2026.

**Comment by esc** [comment]
2.4 support was merged to `main` this morning. https://github.com/numba/numba/pull/10393

**Comment by juntyr** [comment]
What's the timeline for releasing the next version of numba that will be compatible with numpy 2.4?

**Comment by swap357** [comment]
The `0.64.0rc1` release checklist is open - https://github.com/numba/numba/issues/10421.
This is the first RC for Numba `0.64.0` with NumPy 2.4 support, and will be published as release testing completes.

**Comment by swap357** [comment]
All known critical issues related to Numpy2.4 have been addressed and merged to `main`. I've opened issues that are enhancements to get in parity with NumPy behavior, and are more involved - 
https://github.com/numba/numba/issues/10416
https://github.com/numba/numba/issues/10415
These are improvements that are not release blockers for NumPy2.4 support and will be addressed on subsequent releases.

**Comment by swap357** [comment]
Numba `0.64.0rc1` is now released with NumPy2.4 support -
https://numba.discourse.group/t/ann-numba-0-64-0rc1-numpy-2-4-support/3225
If you maintain software that depends on Numba, please help us test this RC and report anything you find here.

**Comment by swap357** [comment]
Numba `0.64.0` was released with NumPy2.4 support- https://pypi.org/project/numba/0.64.0. The removals and major changes were addressed. The alignment regarding future deprecations, improvements that can be made on Numba have been noted on issues. And hence, closing this issue.
