### ISSUE TITLE
Regression in 0.53rc2: axis= parameter in gufuncs

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#6773]
This broke in 0.53rc2; it was working in 0.52:

```python
import numba
import numpy

@numba.guvectorize(["f8[:],f8[:]"], "(n)->(n)")
def my_cumsum(x, res):
    acc = 0
    for i in range(x.shape[0]):
        acc += x[i]
        res[i] = acc


x = numpy.ones((20, 30))
y = my_cumsum(x, axis=0)
```
Output:
```
TypeError: __call__() got an unexpected keyword argument 'axis'
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a regression.
