### PR TITLE
CUDA: Fix and deprecate `inspect_ptx()`, fix NVVM option setup for device functions

### LINKED ISSUE #6950: Numba master breaks cuDF
Failures with cuDF branch-0.20 with Numba master:

```
FAILED cudf/tests/test_udf_binops.py::test_generic_ptx[float32] - numba.cuda.cudadrv.error.NvvmError: Failed to compile
FAILED cudf/tests/test_udf_binops.py::test_generic_ptx[float64] - numba.cuda.cudadrv.error.NvvmError: Failed to compile
FAILED cudf/tests/test_udf_binops.py::test_generic_ptx[int16] - numba.cuda.cudadrv.error.NvvmError: Failed to compile
FAILED cudf/tests/test_udf_binops.py::test_generic_ptx[int32] - numba.cuda.cudadrv.error.NvvmError: Failed to compile
FAILED cudf/tests/test_udf_binops.py::test_generic_ptx[int64] - numba.cuda.cudadrv.error.NvvmError: Failed to compile
FAILED cudf/tests/test_udf_binops.py::test_generic_ptx[uint16] - numba.cuda.cudadrv.error.NvvmError: Failed to compile
FAILED cudf/tests/test_udf_binops.py::test_generic_ptx[uint32] - numba.cuda.cudadrv.error.NvvmError: Failed to compile
FAILED cudf/tests/test_udf_binops.py::test_generic_ptx[uint64] - numba.cuda.cudadrv.error.NvvmError: Failed to compile
FAILED cudf/tests/test_udf_binops.py::test_generic_ptx[uint8] - numba.cuda.cudadrv.error.NvvmError: Failed to compile
```

because of e.g.:

```
__________________________________________________________________________________________________________________________________________________ test_generic_ptx[uint8] __________________________________________________________________________________________________________________________________________________

dtype = 'uint8'

    @pytest.mark.parametrize(
        "dtype", sorted(list(dtypeutils.NUMERIC_TYPES - {"int8"}))
    )
    def test_generic_ptx(dtype):
    
        size = 500
    
        lhs_arr = np.random.random(size).astype(dtype)
        lhs_col = Series(lhs_arr)._column
    
        rhs_arr = np.random.random(size).astype(dtype)
        rhs_col = Series(rhs_arr)._column
    
        @numba.cuda.jit(device=True)
        def generic_function(a, b):
            return a ** 3 + b
    
        nb_type = numpy_support.from_dtype(np.dtype(dtype))
        type_signature = (nb_type, nb_type)
    
        result = generic_function.compile(type_signature)
>       ptx = generic_function.inspect_ptx(type_signature)

cudf/tests/test_udf_binops.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../numba/numba/cuda/compiler.py:319: in inspect_ptx
    ptx = nvvm.llvm_to_ptx(llvmir, opt=opt, arch=arch, **nvvm_options)
../../../numba/numba/cuda/cudadrv/nvvm.py:708: in llvm_to_ptx
    ptx = cu.compile(**opts)
../../../numba/numba/cuda/cudadrv/nvvm.py:294: in compile
    self._try_error(err, 'Failed to compile\n')
../../../numba/numba/cuda/cudadrv/nvvm.py:312: in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <numba.cuda.cudadrv.nvvm.NVVM object at 0x7f31684ae910>, error = 9, msg = "Failed to compile\n\n<unnamed> (85, 24): parse invalid redefinition of function '_ZN5numba7cpython7numbers14int_power_impl12$3clocals$3e14int_power$2416Eyx'", exit = False

    def check_error(self, error, msg, exit=False):
        if error:
            exc = NvvmError(msg, RESULT_CODE_NAMES[error])
            if exit:
                print(exc)
                sys.exit(1)
            else:
>               raise exc
E               numba.cuda.cudadrv.error.NvvmError: Failed to compile
E               
E               <unnamed> (85, 24): parse invalid redefinition of function '_ZN5numba7cpython7numbers14int_power_impl12$3clocals$3e14int_power$2416Eyx'
E               NVVM_ERROR_COMPILATION

../../../numba/numba/cuda/cudadrv/nvvm.py:192: NvvmError
```

Minimal reproducer:

```python
from numba import cuda, types

@cuda.jit(device=True)
def generic_function(a, b):
    return a ** 3 + b

type_signature = (types.int8, types.int8)
generic_function.compile(type_signature)
generic_function.inspect_ptx(type_signature)
```

produces:

```
$ python repro.py 
Traceback (most recent call last):
  File "repro.py", line 11, in <module>
    generic_function.inspect_ptx(type_signature)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 319, in inspect_ptx
    ptx = nvvm.llvm_to_ptx(llvmir, opt=opt, arch=arch, **nvvm_options)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/nvvm.py", line 708, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/nvvm.py", line 294, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/nvvm.py", line 312, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/nvvm.py", line 192, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (85, 24): parse invalid redefinition of function '_ZN5numba7cpython7numbers14int_power_impl12$3clocals$3e13int_power$242Exx'
NVVM_ERROR_COMPILATION
```

### PR DESCRIPTION
**Pull request by gmarkall**
This fixes issues with device functions:

- `inspect_ptx` was broken by PR #6735 (commit 11a7397). The device  function should use the code library to obtain the PTX instead of attempting to compile directly itself.
- Optimization and debug options were not passed to NVVM when compiling device functions. These options are now set up and passed to `compile_cuda` when a device function is compiled.

This commit also deprecates the use of `inspect_ptx` - the preferred API for compiling Python to PTX is to use the `compile_ptx` function instead. The `inspect_ptx()` method had a couple of issues:

- Allowing it to receive a dict of options for NVVM enabled it to produce different PTX to what might actually have been compiled so far, as highlighted by the fact that optimization and debug flags failed to be passed to NVVM for the `compile()` method, but not in the `inspect_ptx()` method.
- The NVVM options dict kwarg was unsafely initialized anyway (`nvvm_options={}`) - See issue #5811.
- It returned encoded bytes, which differs from similar APIs (e.g. `inspect_llvm()`, and the Dispatcher's `inspect_asm()`, which return `str` instead.

As there is no easy way to correctly and consistently pass NVVM options through `inspect_ptx()`, a warning is emitted stating that these are ignored if a user passes any options in.

Some tests are also added, to ensure that it works correctly, and warns the user appropriately.

Fixes #6950.

### CODE REVIEW

File: numba/cuda/compiler.py [hunk 1]
```diff
@@ -260,8 +260,13 @@ def compile(self, args):
...
         """
         if args not in self._compileinfos:
+            nvvm_options = {
+                'opt': 3 if self.opt else 0,
+                'debug': self.debug,
+            }
+
             cres = compile_cuda(self.py_func, None, args, debug=self.debug,
-                                inline=self.inline)
+                                inline=self.inline, nvvm_options=nvvm_options)
```
Comment (stuartarchibald) [inline numba/cuda/compiler.py:269]: Whilst this replicates the `opt` behaviour in `inspect_ptx` is this now changing the default optimisation behaviour for callers of this method? Was it just being ignored before/something else would override it (direct inlining)?

File: numba/cuda/compiler.py [hunk 2]
```diff
@@ -309,15 +310,15 @@ def inspect_ptx(self, args, nvvm_options={}):
...
-        return ptx
+        msg = ('inspect_ptx for device functions is deprecated. Use '
+               'compile_ptx instead.')
+        warn(msg, category=NumbaDeprecationWarning)
+
+        if nvvm_options:
+            msg = ('nvvm_options are ignored. Use compile_ptx if you want to '
+                   'set NVVM options.')
+            warn(msg, category=NumbaDeprecationWarning)
+        return self.compile(args).library.get_asm_str().encode()
```
Comment (stuartarchibald) [inline numba/cuda/compiler.py:321]: Add a note in the deprecation notices?

**Review by stuartarchibald — COMMENTED** [review]
Thanks for the patch, looks good. Just a couple of minor queries to resolve. Thanks again.

File: numba/cuda/compiler.py (hunk 1 above)
Comment (gmarkall) [reply numba/cuda/compiler.py:269]: It's fixing the optimization behaviour - even if you passed `opt=False`, it would still optimize because we passed nothing to NVVM and it optimizes by default. Worse, the test case that checked this (`numba.cuda.tests.cudapy.test_optimization.TestOptimization.test_device_noopt`) was erroneously passing because of the incorrect implementation of `inspect_ptx`! Once I fixed the behaviour of `inspect_ptx()`, this test started failing, highlighting the need for the change on the line these comments pertain to.

File: numba/cuda/compiler.py (hunk 2 above)
Comment (gmarkall) [reply numba/cuda/compiler.py:321]: Done.

File: numba/cuda/compiler.py (hunk 1 above)
Comment (stuartarchibald) [reply numba/cuda/compiler.py:269]: Thanks for the explanation. Seems like this is doing the correct behaviour now!

File: numba/cuda/compiler.py (hunk 2 above)
Comment (stuartarchibald) [reply numba/cuda/compiler.py:321]: Thanks. Doc build https://numba--6953.org.readthedocs.build/en/6953/reference/deprecation.html#deprecation-of-the-inspect-ptx-method looks good.

**Comment by stuartarchibald** [comment]
@gmarkall many thanks for the updates. Please could you resolve the conflict and then this can be run through the farm? Thanks again!

**Comment by gmarkall** [comment]
> @gmarkall many thanks for the updates. Please could you resolve the conflict and then this can be run through the farm? Thanks again!

Thanks for the review - the conflicts are fixed but the tests fail due to master being broken for CUDA at the moment, e.g.:

```
======================================================================
ERROR: test_array_assign_all (numba.cuda.tests.cudadrv.test_cuda_array_slicing.CudaArraySetting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudadrv/test_cuda_array_slicing.py", line 273, in test_array_assign_all
    darr[:] = _400
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/devices.py", line 224, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/devicearray.py", line 570, in __setitem__
    return self._do_setitem(key, value)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/devicearray.py", line 628, in _do_setitem
    _assign_kernel(lhs.ndim).forall(n_elements, stream=stream)(lhs, rhs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 438, in __call__
    kernel = self.kernel.specialize(*args)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 990, in specialize
    specialization = Dispatcher(self.py_func, [types.void(*argtypes)],
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 868, in __init__
    self.compile(sigs[0])
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 1055, in compile
    kernel = _Kernel(self.py_func, argtypes, link=self.link,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 481, in __init__
    cres = compile_cuda(self.py_func, types.void, self.argtypes,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 157, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 675, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 419, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 483, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 462, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 453, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 105, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 83, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1071, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in cuda mode pipeline (step: nopython frontend)
No implementation of function Function(<intrinsic to_fixed_tuple>) found for signature:
 
 >>> to_fixed_tuple(array(int64, 1d, C), Literal[int](2))
 
There are 2 candidate implementations:
     - Of which 2 did not match due to:
     Intrinsic in function 'to_fixed_tuple': File: numba/np/unsafe/ndarray.py: Line 41.
       With argument(s): '(array(int64, 1d, C), int64)':
      Rejected as the implementation raised a specific error:
        KeyError: <class 'numba.core.extending_hardware.CUDA'>
  raised from /home/gmarkall/numbadev/numba/numba/core/registry.py:99

During: resolving callee type: Function(<intrinsic to_fixed_tuple>)
During: typing of call at /home/gmarkall/numbadev/numba/numba/cuda/cudadrv/devicearray.py (452)


File "numba/cuda/cudadrv/devicearray.py", line 452:
    def kernel(lhs, rhs):
        <source elided>

        lhs[to_fixed_tuple(idx[0], ndim)] = rhs[to_fixed_tuple(idx[1], ndim)]
        ^
```

**Comment by gmarkall** [comment]
@stuartarchibald Now that master is fixed, this PR is working locally for me again - I've merged in master too.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch and fixes.

**Comment by stuartarchibald** [comment]
> Buildfarm ID: `numba_smoketest_cuda_yaml_54`.

Passed.
