### ISSUE TITLE
compiling code ahead of time error with latest version 0.60.0

### ISSUE THREAD

**Issue by ZebinYang** [numba/numba#9656]
## Reporting a bug

- [Y] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [Y] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I am using compiling code ahead of time, but the compilation fails with the following error.

- Python: 3.12
- numba: 0.60.0
- system: Linux-x86

```
from numba.pycc import CC

cc = CC('my_module')
# Uncomment the following line to print out the compilation steps
#cc.verbose = True

@cc.export('multf', 'f8(f8, f8)')
@cc.export('multi', 'i4(i4, i4)')
def mult(a, b):
    return a * b

@cc.export('square', 'f8(f8)')
def square(a):
    return a ** 2

if __name__ == "__main__":
    cc.compile()

numba/cext/dictobject.c:1041:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned int shift = 1; shift < sizeof(Py_ssize_t) * CHAR_BIT; shift <<= 1) {
     ^
/root/anaconda3/envs/py311/lib/python3.11/site-packages/numba/cext/dictobject.c:1041:5: note: use option -std=c99 or -std=gnu99 to compile your code
```

The same code can run well with Python 3.7-3.10 and numba==0.56.

**Comment by stuartarchibald** [comment]
Thanks for the report. From the error message it looks the there is an issue with the compiler used by `pycc` not accepting source code containing C99 standard features.

Numba contains source code that uses C99 features and so the native compiler used by `pycc` must support C99 and appropriate flags must be set to ensure it compiles assuming the C99 standard. I would guess that this has appeared in the move to Numba 0.60 as #8183 (which was added in Numba 0.57.0) introduced the C99 syntax.

Could you perhaps set/update the `CFLAGS` environment variable to permit use of C99 features in your compiler?

**Comment by ZebinYang** [comment]
Hi @stuartarchibald,

Thank you. I have tried this approach by setting CFLAGS=-std-C99, but it triggered another error. The new error message is 
```
C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
```

I also tried other ways to solve it, and finally, the issue got solved after I upgraded gcc from 4.8.5 to 11.2.1.
