### ISSUE TITLE
BUG cannot set items in structured array data types in 0.54.0

### ISSUE THREAD

**Issue by beckermr** [numba/numba#7355]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Here is the code sample:

```
import numpy as np
from numba import njit


@njit
def set_field(arr):
    arr['a'][:] = 0.0


if __name__ == "__main__":
    for _ in range(10):
        arr = np.ones(1, dtype=[('a', 'f8', (6,))])
        set_field(arr[0])
        assert np.all(arr['a'] == 0)
```

This code sample works with 0.53.1 but does not work on 0.54.0. Here is the error

```
Traceback (most recent call last):
  File "/Users/beckermr/Desktop/numba_bug.py", line 13, in <module>
    set_field(arr[0])
  File "/Users/beckermr/miniconda3/envs/numba-bug/lib/python3.9/site-packages/numba/core/dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/beckermr/miniconda3/envs/numba-bug/lib/python3.9/site-packages/numba/core/dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(nestedarray(float64, (6,)), slice<a:b>, float64)
 
There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(nestedarray(float64, (6,)), slice<a:b>, float64)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'SetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 171.
    With argument(s): '(nestedarray(float64, (6,)), slice<a:b>, float64)':
   Rejected as the implementation raised a specific error:
     TypeError: __init__() got an unexpected keyword argument 'ndim'
  raised from /Users/beckermr/miniconda3/envs/numba-bug/lib/python3.9/site-packages/numba/core/types/abstract.py:66

During: typing of staticsetitem at /Users/beckermr/Desktop/numba_bug.py (7)

File "numba_bug.py", line 7:
def set_field(arr):
    arr['a'][:] = 0.0
```

A conda env with the correct versions pulled from conda-forge should be sufficient to reproduce the bug on either OSX or Linux.

cc @esheldon

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. `git bisect` suggests: 0b9496cd2a47ad63478443ee855cbe050ed67a23 introduced this.

**Comment by stuartarchibald** [comment]
The issue is here:
https://github.com/numba/numba/blob/9d135798227b5a3612fe4e2401471efd9b333302/numba/core/types/npytypes.py#L455-L457
in the MWR above, `self` is an instance of a `NestedArray` and the `NestedArray` ctor doesn't match the args provided:
https://github.com/numba/numba/blob/9d135798227b5a3612fe4e2401471efd9b333302/numba/core/types/npytypes.py#L549-L556

**Comment by gmarkall** [comment]
This might also be an instance of the same problem, from: https://numba.discourse.group/t/incompatible-functions-with-nested-arrays/883

```python
import numpy as np
import numba as nb

DTYPE = np.dtype([(‘X1’, np.float64, 4)])

@nb.njit
def fun():
    structured_array = np.zeros(5, dtype=DTYPE)
    X1 = np.copy(structured_array[0]['X1'])
    print(X1)
    return

fun()
```

which produces:

```
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/7355/repro.py", line 15, in <module>
    fun()
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function copy at 0x7f0f821c28b0>) found for signature:
 
 >>> copy(nestedarray(float64, (4,)))
 
There are 4 candidate implementations:
  - Of which 4 did not match due to:
  Overload in function '_OverloadWrapper._build.<locals>.ol_generated': File: numba/core/overload_glue.py: Line 131.
    With argument(s): '(nestedarray(float64, (4,)))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<intrinsic stub>) found for signature:
    
    >>> stub(nestedarray(float64, (4,)))
    
   There are 2 candidate implementations:
     - Of which 2 did not match due to:
     Intrinsic in function 'stub': File: numba/core/overload_glue.py: Line 35.
       With argument(s): '(nestedarray(float64, (4,)))':
      Rejected as the implementation raised a specific error:
        TypeError: __init__() got an unexpected keyword argument 'ndim'
     raised from /home/gmarkall/numbadev/numba/numba/core/types/abstract.py:66
   
   During: resolving callee type: Function(<intrinsic stub>)
   During: typing of call at <string> (3)
   
   
   File "<string>", line 3:
   <source missing, REPL/exec in use?>

  raised from /home/gmarkall/numbadev/numba/numba/core/typeinfer.py:1074

During: resolving callee type: Function(<function copy at 0x7f0f821c28b0>)
During: typing of call at /home/gmarkall/numbadev/issues/7355/repro.py (10)


File "repro.py", line 10:
def fun():
    <source elided>
    structured_array = np.zeros(5, dtype=DTYPE)
    X1 = np.copy(structured_array[0]['X1'])
```

**Comment by stuartarchibald** [comment]
Other related issues, kindly reported here https://numba.discourse.group/t/incompatible-functions-with-nested-arrays/883/5:

```python
@njit
def fun():
    structured_array = np.zeros(5, dtype=DTYPE)
    X1 = structured_array[0][‘X1’].flatten() #doesn’t work in 0.54.0
    X1 = np.ascontiguousarray(structured_array[0][‘X1’]) #doesn’t work in 0.54.0
    print(X1)
    return

fun()
```
and
```python
@njit
def fun():
    structured_array = np.zeros(5, dtype=DTYPE)
    print(structured_array) #OK
    print(structured_array[0][‘X1’]) #OK
    print(np.min(structured_array[0][‘X1’])) #OK
    print(np.max(structured_array[0][‘X1’])) #NOK: -9.868309920863368e+148
    return
```
I think the latter is probably the known lifetime issue with structured array element references.

**Comment by jason-s** [comment]
Does the fix for this issue cover reading from nested arrays as well?

https://numba.discourse.group/t/incompatible-functions-with-nested-arrays/883/7?u=jason_s

**Comment by sklam** [comment]
Bug fix merged and available in 0.54.1
