### ISSUE TITLE
'pip install numba' does not work on python 3.4

### ISSUE THREAD

**Issue by guziy** [numba/numba#1215]
I get the following error:

```
numba/runtime/_nrt_python.c:2:17: fatal error: nrt.h: No such file or directory
```

Everything works when using the github version.

My python (working in virtualenv):
```
Python 3.4.3 (default, Apr  4 2015, 14:09:21)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

My system:
Linux

Cheers

**Comment by seibert** [comment]
Yeah, we found a last minute packaging problem with the tar file we put on PyPI.  There should be a version 0.19.2 by the end of the day that fixes this.

**Comment by seibert** [comment]
OK, this should be fixed now.  Thanks for the bug report!
