### ISSUE TITLE
 AttributeError: 'Integer' object has no attribute 'literal_value' #115 

### ISSUE THREAD

**Issue by kp992** [numba/numba#9634]
There is a library `interpolation.py` (https://github.com/EconForge/interpolation.py) that depends on numba. I am trying to use a function `eval_linear` from `interpolation` which is now failing with the following error:

```py
File ~/mambaforge/envs/qe/lib/python3.10/site-packages/interpolation/splines/eval_splines.py:100, in __eval_spline(grid, C, points, out, k, diff, extrap_mode)
     98 @overload(_eval_spline)
     99 def __eval_spline(grid, C, points, out=None, k=1, diff="None", extrap_mode="linear"):
--> 100     kk = (k).literal_value
    101     diffs = (diff).literal_value
    102     extrap_ = (extrap_mode).literal_value

AttributeError: 'Integer' object has no attribute 'literal_value'
```

This is the script to reproduce the error:

```py
import numpy as np
from interpolation.splines import UCGrid, nodes, eval_linear

# Define the function to interpolate
f = lambda x, y: np.sin(np.sqrt(x**2 + y**2 + 0.00001)) / np.sqrt(x**2 + y**2 + 0.00001)

# Create a uniform cartesian grid
grid = UCGrid((-1.0, 1.0, 10), (-1.0, 1.0, 10))

# Get grid points
gp = nodes(grid)  # 100x2 matrix

# Compute values on grid points
values = f(gp[:, 0], gp[:, 1]).reshape((10, 10))

# Interpolate at one point
point = np.array([0.1, 0.45])  # 1D array

# Interpolation
val = eval_linear(grid, values, point)  # Should return a float

print("Interpolated value at point", point, "is", val)
```

How can this be fixed? Or are they any work arounds? The error is coming from: https://github.com/EconForge/interpolation.py/blob/16c106fe857150d445e1c918b07da5da45d64a9b/interpolation/splines/eval_splines.py#L213

Numba version: `0.60`

**Comment by kp992** [comment]
This works fine with `numba-0.59.1`.

**Comment by gmarkall** [comment]
I'm not able to get this to work with Numba 0.59.1 either. Can you post the outputs from `numba -s` in your working and non-working setups please?

**Comment by gmarkall** [comment]
I see that other users report that 2.2.4 used to work, in https://github.com/EconForge/interpolation.py/issues/115 - it's probably better to continue tracking down the issue with the interpolation.py maintainers, unless a reproducer that shows the error outside of interpolate.py can be provided.

**Comment by kp992** [comment]
> Can you post the outputs from numba -s in your working and non-working setups please?

Please see the output:

<details>
<summary>Output</summary>
<p>

```bash
% numba -s
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2024-07-02 19:14:36.306136
UTC start time                                : 2024-07-02 13:44:36.306139
Running time (s)                              : 4.926997

__Hardware Information__
Machine                                       : arm64
CPU Name                                      : cyclone
CPU Count                                     : 8
Number of accessible CPUs                     : ?
List of accessible CPUs cores                 : ?
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 

Memory Total (MB)                             : 8192
Memory Available (MB)                         : 3280

__OS Information__
Platform Name                                 : macOS-13.0-arm64-arm-64bit
Platform Release                              : 22.1.0
OS Name                                       : Darwin
OS Version                                    : Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
OS Specific Version                           : 13.0   arm64
Libc Version                                  : ?

__Python Information__
Python Compiler                               : Clang 15.0.7 
Python Implementation                         : CPython
Python Version                                : 3.10.12
Python Locale                                 : None.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.59.1
llvmlite Version                              : 0.42.0

__LLVM Information__
LLVM Version                                  : 14.0.6

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Runtime Version                          : ?
CUDA NVIDIA Bindings Available                : ?
CUDA NVIDIA Bindings In Use                   : ?
CUDA Minor Version Compatibility Available    : ?
CUDA Minor Version Compatibility Needed       : ?
CUDA Minor Version Compatibility In Use       : ?
CUDA Detect Output:
None
CUDA Libraries Test Output:
None

__NumPy Information__
NumPy Version                                 : 1.26.3
NumPy Supported SIMD features                 : ('NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD', 'FPHP', 'ASIMDHP', 'ASIMDDP')
NumPy Supported SIMD dispatch                 : ('ASIMDHP', 'ASIMDFHM')
NumPy Supported SIMD baseline                 : ('NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD')
NumPy AVX512_SKX support detected             : False

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: Intel
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda Build                                   : not installed
Conda Env                                     : 23.3.1
Conda Platform                                : osx-arm64
Conda Python Version                          : 3.10.12.final.0
Conda Root Writable                           : True

__Installed Packages__
accessible-pygments       0.0.4                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
anyio                     4.0.0                    pypi_0    pypi
appnope                   0.1.3                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
arviz                     0.13.0                   pypi_0    pypi
asttokens                 2.4.0                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2024.2.2             hf0a4a13_0    conda-forge
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
cftime                    1.6.2                    pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.1.4                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dask                      2023.9.2                 pypi_0    pypi
debugpy                   1.8.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
distributed               2023.9.2                 pypi_0    pypi
docutils                  0.18.1                   pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
exceptiongroup            1.1.3                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.18.0                   pypi_0    pypi
filelock                  3.13.1             pyhd8ed1ab_0    conda-forge
flake8                    6.1.0                    pypi_0    pypi
fonttools                 4.42.1                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               hadb7bae_2    conda-forge
fsspec                    2023.9.2                 pypi_0    pypi
ghp-import                1.1.0                    pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.37                   pypi_0    pypi
gmp                       6.3.0                h965bd2d_0    conda-forge
gmpy2                     2.1.2           py310h2e6cad2_1    conda-forge
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.25.2                   pypi_0    pypi
ipython                   8.15.0                   pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jax                       0.4.23                   pypi_0    pypi
jaxlib                    0.4.23                   pypi_0    pypi
jedi                      0.19.0                   pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.19.1                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
jupyter-book              0.15.1                   pypi_0    pypi
jupyter-cache             0.6.1                    pypi_0    pypi
jupyter-client            8.3.1                    pypi_0    pypi
jupyter-core              5.3.1                    pypi_0    pypi
jupyter-events            0.7.0                    pypi_0    pypi
jupyter-lsp               2.2.1                    pypi_0    pypi
jupyter-server            2.7.3                    pypi_0    pypi
jupyter-server-mathjax    0.2.6                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab                4.1.8                    pypi_0    pypi
jupyterlab-myst           2.1.0                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.27.1                   pypi_0    pypi
jupytext                  1.16.1                   pypi_0    pypi
kaleido                   0.2.1                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
latexcodec                2.0.1                    pypi_0    pypi
lcms2                     2.16                 ha0e7c42_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20230802.1      cxx17_h13dd4ca_0    conda-forge
libblas                   3.9.0           21_osxarm64_openblas    conda-forge
libcblas                  3.9.0           21_osxarm64_openblas    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.19                 hb547adb_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_2    conda-forge
libgfortran5              13.2.0               hf226fd6_2    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           21_osxarm64_openblas    conda-forge
libopenblas               0.3.26          openmp_h6c19121_0    conda-forge
libpng                    1.6.42               h091b4b1_0    conda-forge
libprotobuf               4.24.4               h810fc01_0    conda-forge
libsass                   0.20.1                   pypi_0    pypi
libsqlite                 3.43.0               hb31c410_0    conda-forge
libtiff                   4.6.0                ha8a6c65_2    conda-forge
libtorch                  2.1.2           cpu_generic_h79a1481_0    conda-forge
libuv                     1.46.0               hb547adb_0    conda-forge
libwebp-base              1.3.2                hb547adb_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
linkify-it-py             2.0.2                    pypi_0    pypi
llvm-openmp               17.0.6               hcd81f8e_0    conda-forge
llvmlite                  0.42.0                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.8.4                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdit-py-plugins           0.3.5                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   3.0.1                    pypi_0    pypi
ml-dtypes                 0.3.2                    pypi_0    pypi
mpc                       1.3.1                h91ba8db_0    conda-forge
mpfr                      4.2.1                h9546428_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msgpack                   1.0.6                    pypi_0    pypi
multipledispatch          1.0.0                    pypi_0    pypi
myst-nb                   0.17.2                   pypi_0    pypi
myst-parser               0.18.1                   pypi_0    pypi
nbclient                  0.7.4                    pypi_0    pypi
nbconvert                 7.8.0                    pypi_0    pypi
nbdime                    3.2.1                    pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
ncurses                   6.4                  h7ea286d_0    conda-forge
nest-asyncio              1.5.8                    pypi_0    pypi
netcdf4                   1.6.4                    pypi_0    pypi
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
notebook                  7.1.3                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numba                     0.59.1                   pypi_0    pypi
numpy                     1.26.0                   pypi_0    pypi
numpyro                   0.13.2                   pypi_0    pypi
openjpeg                  2.5.0                h4c1507b_3    conda-forge
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   3.2.1                h0d3ecfb_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
overrides                 7.4.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.4.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.0.1                   pypi_0    pypi
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0                   pypi_0    pypi
plotly                    5.19.0                   pypi_0    pypi
pluggy                    1.4.0                    pypi_0    pypi
prometheus-client         0.17.1                   pypi_0    pypi
prompt-toolkit            3.0.39                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pybtex                    0.24.0                   pypi_0    pypi
pybtex-docutils           1.0.3                    pypi_0    pypi
pycodestyle               2.11.1                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydata-sphinx-theme       0.14.1                   pypi_0    pypi
pyenchant                 3.2.2                    pypi_0    pypi
pyflakes                  3.1.0                    pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pyro-api                  0.1.2                    pypi_0    pypi
pyro-ppl                  1.8.6                    pypi_0    pypi
pyspellchecker            0.8.1                    pypi_0    pypi
pytest                    8.1.0                    pypi_0    pypi
python                    3.10.12         h01493a6_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python_abi                3.10                    4_cp310    conda-forge
pytorch                   2.1.2           cpu_generic_py310h4d6d75d_0    conda-forge
pytorch-cpu               2.1.2           cpu_generic_py310hc3bfeb3_0    conda-forge
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.1                   pypi_0    pypi
quantecon                 0.7.2                    pypi_0    pypi
quantecon-book-theme      0.5.3                    pypi_0    pypi
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.30.2                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rjsmin                    1.1.0                    pypi_0    pypi
rpds-py                   0.10.3                   pypi_0    pypi
scipy                     1.11.2                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h156473d_2    conda-forge
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sphinx                    5.0.2                    pypi_0    pypi
sphinx-book-theme         1.0.1                    pypi_0    pypi
sphinx-comments           0.0.3                    pypi_0    pypi
sphinx-copybutton         0.5.2                    pypi_0    pypi
sphinx-design             0.3.0                    pypi_0    pypi
sphinx-exercise           0.4.1                    pypi_0    pypi
sphinx-external-toc       0.3.1                    pypi_0    pypi
sphinx-jupyterbook-latex  0.5.2                    pypi_0    pypi
sphinx-multitoc-numbering 0.1.3                    pypi_0    pypi
sphinx-thebe              0.2.1                    pypi_0    pypi
sphinx-togglebutton       0.3.1                    pypi_0    pypi
sphinx-tojupyter          0.3.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.7                    pypi_0    pypi
sphinxcontrib-bibtex      2.5.0                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.5                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.4                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.6                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.9                    pypi_0    pypi
sphinxcontrib-youtube     1.1.0                    pypi_0    pypi
sphinxext-rediraffe       0.2.7                    pypi_0    pypi
sqlalchemy                2.0.21                   pypi_0    pypi
stack-data                0.6.2                    pypi_0    pypi
sympy                     1.12            pypyh9d50eac_103    conda-forge
tabulate                  0.9.0                    pypi_0    pypi
tblib                     2.0.0                    pypi_0    pypi
tenacity                  8.2.3                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.13               hb31c410_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.1.2                    pypi_0    pypi
torchvision-cpu           0.2.2                      py_3    pytorch
tornado                   6.3.3                    pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.10.0                   pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.2                    pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.0.5                    pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
web-compile               0.2.3                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.3                    pypi_0    pypi
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xarray                    2023.8.0                 pypi_0    pypi
xarray-einstats           0.6.0                    pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zict                      3.0.0                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zstd                      1.5.5                h4f39d0f_0    conda-forge

No errors reported.


__Warning log__
Warning (cuda): CUDA driver library cannot be found or no CUDA enabled devices are present.
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
--------------------------------------------------------------------------------
```

</p>
</details>

**Comment by sklam** [comment]
I can confirm that the reproducer breaks on the interpolation:HEAD with numba:HEAD and works with numba:0.59.1

**Comment by sklam** [comment]
As we have guessed in the triage meeting, it is indeed caused by defaulting to new_style error. First bad commit: c8789f7910fb41dfd7fc1fd1b594a4d91c684d40. Problem also exist with `NUMBA_CAPTURED_ERRORS=new_style` on 0.59.1

**Comment by sklam** [comment]
Interpolation needs to be patched. The best practice for using literal types is to set `prefer_literal=True` on the `@overload`. Old-style error hides the problem due to the fallback.  Numba tries to not use literal types first, then tries again with using literal types. Old-style error treats all error as recoverable. 

The minimal patch to make it work:

```
diff --git a/interpolation/splines/eval_splines.py b/interpolation/splines/eval_splines.py
index 2e2adc7..7e944a2 100644
--- a/interpolation/splines/eval_splines.py
+++ b/interpolation/splines/eval_splines.py
@@ -95,7 +95,7 @@ def _eval_spline():
     pass
 
 
-@overload(_eval_spline)
+@overload(_eval_spline, prefer_literal=True)
 def __eval_spline(grid, C, points, out=None, k=1, diff="None", extrap_mode="linear"):
     kk = (k).literal_value
     diffs = (diff).literal_value
```

It can be even better if the `@overload` code checks to see of `k` and `diff` are actually literal types.
