### ISSUE TITLE
Shared memory not support boolean type

### ISSUE THREAD

**Issue by hn12404988** [numba/numba#5055]
- [x ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Following code will let numba generate erros,

```
from numba import boolean
import numpy as np

@cuda.jit
def test():
    share_ref = cuda.shared.array(shape=(1, 1), dtype=boolean)
    share_ref[1][1] = True

test[1,1]()
```

No matter I use `boolean`, `bool`, or `np.bool`. They all fail, and the error messages are saying something like this

First kind:
```
unsupported type: bool
```

Second kind:
```
type object 'bool' has no attribute 'is_precise'
```

I checked the doc, and `bool` is supported in cuda. Or, is something I misunderstanding?

**Comment by gmarkall** [comment]
You're right that it's not supported in shared memory in the current release version of Numba, but a PR to support them was just merged yesterday: https://github.com/numba/numba/pull/5014

So this should work in Numba 0.48 - I just tried your reproducer with the current master branch, and it produced no error.

**Comment by sklam** [comment]
Closing because of https://github.com/numba/numba/pull/5014

**Comment by hn12404988** [comment]
Appreciate for the info, I will wait for the officail release of 0.48
