### PR TITLE
Fix test_ufuncs failures depending on libm with Numpy 1.0

### PR DESCRIPTION
**Pull request by pitrou**
This should fix the failures on our OS X and CentOS Jenkins machines.

### CODE REVIEW

**Comment by seibert** [comment]
Can you put the workaround Siu identificed in the cudapy test code into this PR?
https://github.com/numba/numba/blob/master/numba/cuda/tests/cudapy/test_record_dtype.py#L131
```
for i in range(self.sample1d.size):
    got = self.sample1d.copy()
    expect = got.copy()

    cfunc(got, i, value)
    pyfunc(expect, i, value)
```

**Comment by seibert** [comment]
This should let you also reenable Numpy 1.10 on Travis-CI.

**Comment by pitrou** [comment]
The workaround doesn't work on Numpy 1.9:
```
======================================================================
ERROR: test_set_a (numba.cuda.tests.cudapy.test_record_dtype.TestRecordDtypeWithStructArrays)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antoine/numba/numba/cuda/tests/cudapy/test_record_dtype.py", line 139, in test_set_a
    self._test_set_equal(set_a, 3.1415, types.float64)
  File "/home/antoine/numba/numba/cuda/tests/cudapy/test_record_dtype.py", line 133, in _test_set_equal
    pyfunc(expect, i, value)
  File "/home/antoine/numba/numba/cuda/tests/cudapy/test_record_dtype.py", line 12, in set_a
    ary[i].a = v
AttributeError: 'numpy.void' object has no attribute 'a'
```

**Comment by seibert** [comment]
OK, let's figure this out in a new PR.
