### ISSUE TITLE
AttributeError when allocating "list" in device if NUMBA_ENABLE_CUDASIM=1

### ISSUE THREAD

**Issue by jetxeberria** [numba/numba#4800]
Numba version: 0.46.0

This code (minimal_testing.py):

```python
from numba import cuda

@cuda.jit()
def foo(d):
    d[:] = (10, 10)

d = cuda.to_device(list(range(2)))
foo[1, 1](d)
print(d.copy_to_host())
```

- Works if called with:
```
python minimal_testing.py
```
Outputs:

```
[10 10]
```

- But raises AttributeError if called with:
```
NUMBA_ENABLE_CUDASIM=1 python minimal_test.py
```
Error traceback:
```
Traceback (most recent call last):
  File "minimal_testing.py", line 13, in <module>
    d = cuda.to_device(list(range(2)))
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/simulator/cudadrv/devicearray.py", line 191, in to_device
    sentry_contiguous(ary)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/simulator/cudadrv/devicearray.py", line 172, in sentry_contiguous
    core = array_core(ary)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/simulator/cudadrv/devicearray.py", line 163, in array_core
    if not ary.strides:
AttributeError: 'list' object has no attribute 'strides'
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Think this is an issue where `cuda.to_device` under the simulator needs to replicate what happens in the actual implementation (i.e. list accepted).

**Comment by gmarkall** [comment]
I can no longer reproduce this - I suspect it was fixed by https://github.com/numba/numba/commit/9a3f130204

@jetxeberria Does it work for you with Numba 0.48.0rc1?

**Comment by jetxeberria** [comment]
Right! It works with Numba=0.48.0

**Comment by esc** [comment]
@jetxeberria @gmarkall thanks for following up on this!
