### ISSUE TITLE
Bug in the compiler in 0.60 : 'tuple' object has no attribute 'name'

### ISSUE THREAD

**Issue by Kh4L** [numba/numba#9678]
## Reporting a bug

This bug appeared after upgrading from 0.59 to 0.60.

- [X] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/ppr.py", line 113, in get_ppr
    cols, weights = _get_ppr_numba(
  File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 442, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 375, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 905, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 80, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 94, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 107, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 744, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 438, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 506, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 481, in _compile_core
    raise e
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 472, in _compile_core
    pm.run(self.state)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/typed_passes.py", line 468, in run_pass
    lower.lower()
  File "/usr/local/lib/python3.10/dist-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/lowering.py", line 226, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/usr/local/lib/python3.10/dist-packages/numba/core/lowering.py", line 256, in lower_function_body
    self.lower_block(block)
  File "/usr/local/lib/python3.10/dist-packages/numba/core/lowering.py", line 270, in lower_block
    self.lower_inst(inst)
  File "/usr/local/lib/python3.10/dist-packages/numba/parfors/parfor_lowering.py", line 51, in lower_inst
    _lower_parfor_parallel(self, inst)
  File "/usr/local/lib/python3.10/dist-packages/numba/parfors/parfor_lowering.py", line 67, in _lower_parfor_parallel
    return _lower_parfor_parallel_std(lowerer, parfor)
  File "/usr/local/lib/python3.10/dist-packages/numba/parfors/parfor_lowering.py", line 349, in _lower_parfor_parallel_std
    exp_name_to_tuple_var) = _create_gufunc_for_parfor_body(
  File "/usr/local/lib/python3.10/dist-packages/numba/parfors/parfor_lowering.py", line 1500, in _create_gufunc_for_parfor_body
    hoisted, not_hoisted = hoist(parfor_params, loop_body, typemap, wrapped_blocks)
  File "/usr/local/lib/python3.10/dist-packages/numba/parfors/parfor_lowering.py", line 975, in hoist
    find_setitems_body(setitems, itemsset, loop_body, typemap)
  File "/usr/local/lib/python3.10/dist-packages/numba/parfors/parfor_lowering.py", line 950, in find_setitems_body
    find_setitems_block(setitems, itemsset, block, typemap)
  File "/usr/local/lib/python3.10/dist-packages/numba/parfors/parfor_lowering.py", line 936, in find_setitems_block
    if getattr(typemap[item.name], "mutable", False):
AttributeError: 'tuple' object has no attribute 'name'
```
Repro:
```
from itertools import chain
from typing import Callable, List, Optional, Tuple

import numpy as np

import numba


def _get_ppr(  # pragma: no cover
    rowptr: np.ndarray,
    col: np.ndarray,
    alpha: float,
    eps: float,
    target: Optional[np.ndarray] = None,
) -> Tuple[List[List[int]], List[List[float]]]:

    num_nodes = len(rowptr) - 1 if target is None else len(target)
    alpha_eps = alpha * eps

    for inode_uint in numba.prange(num_nodes):
        inode = numba.int64(inode_uint)

        p = {inode: 0.0}
        r = {}
        r[inode] = alpha
        q = [inode]

        while len(q) > 0:
            unode = q.pop()
            res = r[unode] if unode in r else 0
            if unode in p:
                p[unode] += res
            else:
                p[unode] = res
    return None, None


_get_ppr_numba: Optional[Callable] = None


alpha = 0.2
eps = 1e-5
num_nodes = 128
row = np.random.randint(low=0, high=num_nodes-1, size=(128,), dtype=np.int64)
col = np.random.randint(low=0, high=num_nodes-1, size=(128,), dtype=np.int64)

_get_ppr_numba = numba.jit(nopython=True, parallel=True)(_get_ppr)

cols, weights = _get_ppr_numba(row, col, alpha, eps, None)
```

**Comment by guilhermeleobas** [comment]
Thanks for the report. Can confirm the bug exists in Numba.

An ugly patch that seems to fix the issue:
```diff
diff --git a/numba/parfors/parfor_lowering.py b/numba/parfors/parfor_lowering.py
index 00de2f65b..db2e4c9ac 100644
--- a/numba/parfors/parfor_lowering.py
+++ b/numba/parfors/parfor_lowering.py
@@ -929,9 +929,12 @@ def find_setitems_block(setitems, itemsset, block, typemap):
             rhs = inst.value
             if isinstance(rhs, ir.Expr):
                 if rhs.op in ["build_tuple", "build_list", "build_set", "build_map"]:
-                    for item in rhs.items:
-                        if getattr(typemap[item.name], "mutable", False):
-                            itemsset.add(item.name)
+                    for tup in rhs.items:
+                        if isinstance(tup, ir.Var):
+                            tup = (tup,)
+                        for item in tup:
+                            if getattr(typemap[item.name], "mutable", False):
+                                itemsset.add(item.name)
```
